name: All tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2.1.2

      - name: Install Dependencies
        run: |
          npm install -g truffle
          npm install

      - name: Run Tests
        run: truffle test
