name: All tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '11'

      - name: Install dependencies
        run: |
          npm install -g truffle
          npm install -g ganache-cli
          npm install

      - name: Run ganache
        run: ganache-cli -a 200 &

      - name: Run tests
        run: truffle test
